import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.2)
mengetik('Loading...')
mengetik('Mohon Tunggu...')
mengetik('...............')
mengetik('...............')
mengetik('...............')
mengetik('...............')
mengetik('...............')
mengetik('...............')
mengetik('...............')
mengetik('...............')
mengetik('...............')
mengetik('...............')
mengetik('Meminta Akses...')
mengetik('................')
mengetik('................')
mengetik('................')
mengetik('Meminta Akses Success...')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
mengetik('SYSTEM PROGRAM ACTIVE')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
mengetik('Hai.. Nama Saya SAFA... ^_^')
mengetik('+--------------------------+')
mengetik('SYSTEM ATTACK FACEBOOK ACCOUNT')
mengetik('+--------------------------+')
mengetik('Saya Diciptakan Oleh Tuan Fauzi...')
mengetik('Saya Diciptakan Untuk Membantu...')
mengetik('Saya Diciptakan Untuk Mengambil...')
mengetik('Seluruh Akun Facebook...')
mengetik('+--------------------------+')
mengetik('Semoga Kamu Suka... ^_^')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
